syntax = "proto3";

package layout;

message LayoutBlock {
    string componentId = 1;
    string moduleName = 2;
    string moduleGroup = 3;
    uint32 position = 4;
    bytes data = 5;
    bytes styles = 6;
    repeated LayoutBlock children = 7 [lazy = true];
}

message Layout {
    string templateId = 1;
    bytes settings = 2;
    string layoutId = 3;
    string layoutName = 4;
    string title = 5;
    LayoutBlock jssHeader = 6;
    repeated LayoutBlock jssMain = 7;
    LayoutBlock jssFooter = 8;
}