syntax = "proto3";

package layout;

message LayoutBlock {
    string componentId = 1;
    string parentId = 2;
    string moduleName = 3;
    string moduleGroup = 4;
    uint32 position = 5;
    bytes data = 6;
    bytes styles = 7;
    repeated LayoutBlock children = 8 [lazy = true];
}

message Layout {
    string templateId = 1;
    bytes settings = 2;
    string layoutId = 3;
    string layoutName = 4;
    string title = 5;
    LayoutBlock jssHeader = 6;
    repeated LayoutBlock jssMain = 7;
    LayoutBlock jssFooter = 8;
}